global:
  scrape_timeout: 50s

scrape_configs:
- job_name: 'speedtest'
  scrape_timeout: 5m
  scrape_interval: 15m
  metrics_path: /probe
  static_configs:
  - targets:
    - speedtest-exporter:9516

- job_name: 'ping_exporter'
  static_configs:
  - targets:
    - ping_exporter:9427