{
 "title": "Network Monitor",
 "description": "Default Dashboard of PiMon",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Network Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "download_speed_bps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "cloudflare.com",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(ping_rtt_mean_seconds{target=\"cloudflare.com\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cloudflare.com",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(ping_rtt_mean_seconds{target=\"cloudflare.com\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "1.1.1.1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(ping_rtt_mean_seconds{target=\"1.1.1.1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "1.0.0.1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(ping_rtt_mean_seconds{target=\"1.0.0.1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "8.8.8.8",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(ping_rtt_mean_seconds{target=\"8.8.8.8\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "8.8.4.4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(ping_rtt_mean_seconds{target=\"8.8.4.4\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "upload_speed_bps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "1.0.0.1 Packet Loss",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(ping_loss_ratio{job=\"ping_exporter\", target=\"1.0.0.1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "1.1.1.1 Packet Loss",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(ping_loss_ratio{job=\"ping_exporter\", target=\"1.1.1.1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "8.8.4.4 Packet Loss",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(ping_loss_ratio{job=\"ping_exporter\", target=\"8.8.4.4\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "8.8.8.8 Packet Loss",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(ping_loss_ratio{job=\"ping_exporter\", target=\"8.8.4.4\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}